// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4rz_wUSCLlOZ8wdgRD9pmoj503_QpO0Q',
    appId: '1:296150375110:web:32980238fef610271555c7',
    messagingSenderId: '296150375110',
    projectId: 'communication-87fa6',
    authDomain: 'communication-87fa6.firebaseapp.com',
    storageBucket: 'communication-87fa6.appspot.com',
    measurementId: 'G-XHCCWYC7MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjeeamBNq53NM7QASnNceF3Be21DYHuEQ',
    appId: '1:296150375110:android:65c64a0266ba6d051555c7',
    messagingSenderId: '296150375110',
    projectId: 'communication-87fa6',
    storageBucket: 'communication-87fa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCW5sxeRVCRjMt6YJBgxl9C05_dMMZzBM',
    appId: '1:296150375110:ios:76c09316159e51e41555c7',
    messagingSenderId: '296150375110',
    projectId: 'communication-87fa6',
    storageBucket: 'communication-87fa6.appspot.com',
    iosBundleId: 'com.example.communication.communication',
  );
}
